### ISSUE TITLE
关于目录的问题

### ISSUE THREAD

**Issue by lynzz** [ijse/FED#43]
如我的工程目录是这样的

```
| - fed     #前端资源
  | - mock
| - WEB-INF  #后端文件
  | - template
    | - ftl
```

执行环境 是在 fed 目录里，我执行如下命令

```
fed server -p 3001 -M ./fed/mock --view-root ./ ../
```

mock 不起作用

**Comment by ijse** [comment]
当前版本还不稳定，我会继续做更多测试。

这次全部重写了，可能会跟旧版本有些出入。

谢谢反馈。

**Comment by ijse** [comment]
现在的router规则是根据mock的相对路径进行匹配的，假如你的`mock`目录下有`test.js`，则访问 http://localhost:3001/test 会应用这个mock。

router规则我会再考虑，主要想兼顾方便易用性。

**Comment by lynzz** [comment]
旧版要访问 ftl 文件，都是要手动设置好router，虽不方便，但灵活，现版本对 ftl 的访问是不是如下这个意思。

```
| - view
  | - test
    | - index.ftl
| - mock
  | - test.js
```

是不是这样，我就可访问  localhost:3000/test 了，不用再去手动设置 route 了。

如果是这样，我想 localhost:3000/test.html 这样访问，怎么办？

**Comment by ijse** [comment]
你可以将mock文件更名为`test.html.js`。 mock文件的读取遵循node.js的`require()`查找规则的。

**Comment by ijse** [comment]
@lynzz 

最新版本有所改进，可以使用mock mapping:  https://github.com/ijse/serve2/pull/2

**Comment by lynzz** [comment]
@ijse 谢谢
